# Templated by `cargo-generate` using https://github.com/danielhenrymantilla/proc-macro-template
[lib]
path = "src/_lib.rs"

[package]
name = "droppable-pin"
authors = [
    "Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>",
]
version = "0.1.1"  # Keep in sync
edition = "2024"
rust-version = "1.85.0"

license = "Zlib OR MIT OR Apache-2.0"
repository = "https://github.com/danielhenrymantilla/droppable-pin.rs"
documentation = "https://docs.rs/droppable-pin"
readme = "README.md"

description = "The eponoymous `droppable_pin!` macro around a given `let var = pin!()` declaration allows invoking `pin_drop!` and `pin_set!` on the given `var`, which have in turn been designed to avoid silly borrow-checking errors."
keywords = ["rust-patterns", "pin", "drop", "loop", "dropck"]

[features]
default = [
]

# unstable! Will probably use nightly to improve doc quality
better-docs = []

ui-tests = [
    "better-docs",
]

# `docs-rs` is very similar to `better-docs`, but for it being allowed to enable
# other features as well, often to make sure optional/non-`default` features
# make it to the rendered docs (using `--all-features` instead is not that great).
docs-rs = [
    "better-docs",
]

[dependencies]
maybe-dangling = "0.1.2"
paste = "1.0.15"

[dev-dependencies]
futures-util = "0.3.31"

[workspace]

[package.metadata.docs.rs]
features = [
    "docs-rs",
]
rustdoc-args = [
    # Use (with or without `open`):
    # ```md
    # <details open class="custom"><summary><span class="summary-box"><span>Click to hide</span></span></summary>
    # …
    # </details>
    # ```
    # to get nice drop-down menus (and avoid the css bug with rustdoc).
    "--html-before-content", "fix-docsrs-li-details-summary.html",
]
